// Generated by tools/gen_assets.py from maps/level1.txt. Do not edit.
localparam logic [18:0] START_X = 19'd40960;
localparam logic [18:0] START_Y = 19'd40960;
localparam logic [9:0] START_ANGLE = 10'd0;
