#!/usr/bin/env python3
"""Turn Yosys `stat -json` output into the Markdown resource report
(synth/report.md).  Usage: synth_report.py build/synth/utilization.json [--check]
--check exits non-zero if the design does not fit the XC7S50."""

import json
import re
import sys
from collections import Counter

# Spartan-7 XC7S50 (DS180): 32,600 LUTs, 65,200 flip-flops,
# 75 x 36 Kb block RAM, 120 DSP48E1 slices.
CAPACITY = {"LUT": 32600, "FF": 65200, "BRAM36": 75, "DSP": 120}

BLOCKS = {
    "ray_engine": "ray engine (DDA walk, shared divider)",
    "pixel_pipeline": "pixel pipeline (incl. texture + palette ROMs)",
    "player": "player FSM (incl. sine/cosine ROM)",
    "ram_sdp": "column table (2 x 1280 x 70 bit)",
    "rom_2p": "map ROM (32 x 32 x 4 bit, dual port)",
    "tmds_encoder": "TMDS encoders",
    "video_sig_gen": "video timing",
    "debouncer": "button debouncers",
    "frame_ctrl": "frame controller",
}


def base(name: str) -> str:
    name = re.sub(r"^\$paramod\$?[0-9a-f]*\\", "", name.lstrip("\\"))
    return name.split("\\")[0]


def resolve(mods: dict, t: str):
    """Cell types name submodules with or without Yosys' leading backslash."""
    for k in (t, "\\" + t):
        if k in mods:
            return k
    return None


def totals(mods: dict, name: str, memo: dict) -> Counter:
    if name in memo:
        return memo[name]
    c = Counter()
    for t, n in mods[name]["num_cells_by_type"].items():
        if resolve(mods, t):
            sub = totals(mods, resolve(mods, t), memo)
            for k, v in sub.items():
                c[k] += n * v
        else:
            c[t] += n
    memo[name] = c
    return c


def classify(c: Counter) -> dict:
    lut = sum(v for k, v in c.items() if re.fullmatch(r"LUT[1-6]|INV", k))
    ff = sum(v for k, v in c.items() if re.fullmatch(r"FD[A-Z]*", k))
    bram = c["RAMB36E1"] + c["RAMB18E1"] / 2
    return {"LUT": lut, "FF": ff, "BRAM36": bram, "DSP": c["DSP48E1"], "CARRY4": c["CARRY4"],
            "MUXF7/8": c["MUXF7"] + c["MUXF8"], "RAMB36E1": c["RAMB36E1"], "RAMB18E1": c["RAMB18E1"]}


def fmt(v) -> str:
    return f"{v:g}" if isinstance(v, float) else f"{v:,}"


def main() -> None:
    d = json.load(open(sys.argv[1]))
    mods = d["modules"]
    memo: dict = {}
    top = "\\top_level" if "\\top_level" in mods else "top_level"
    total = classify(totals(mods, top, memo))
    system = next(m for m in mods if base(m) == "raycast_system")

    out = ["# Synthesis report (Yosys, Spartan-7 XC7S50)", "",
           f"Generated by `make synth` with {d.get('creator', 'Yosys').split('(')[0].strip()} "
           "(`synth_xilinx -family xc7 -top top_level`, see `synth/synth.ys`).", "",
           "| Resource | Used | XC7S50 | Share |", "|---|---:|---:|---:|"]
    names = {"LUT": "LUT (LUT1-6, INV)", "FF": "Flip-flops", "BRAM36": "Block RAM (36 Kb units)",
             "DSP": "DSP48E1"}
    for k in ("LUT", "FF", "BRAM36", "DSP"):
        out.append(f"| {names[k]} | {fmt(total[k])} | {CAPACITY[k]:,} | {100 * total[k] / CAPACITY[k]:.1f}% |")
    out += ["", f"Also: {total['CARRY4']} CARRY4, {total['MUXF7/8']} MUXF7/MUXF8, "
            f"block RAM = {total['RAMB36E1']} RAMB36E1 + {total['RAMB18E1']} RAMB18E1.", "",
            "Per block (inside `raycast_system`):", "",
            "| Block | Instances | LUT | FF | BRAM36 | DSP |", "|---|---:|---:|---:|---:|---:|"]
    rows = Counter()
    per = {}
    for t, n in mods[system]["num_cells_by_type"].items():
        if resolve(mods, t):
            b = base(t)
            c = classify(totals(mods, resolve(mods, t), memo))
            rows[b] += n
            acc = per.setdefault(b, Counter())
            for k in ("LUT", "FF", "BRAM36", "DSP"):
                acc[k] += n * c[k]
    for b in sorted(per, key=lambda b: -per[b]["LUT"]):
        c = per[b]
        out.append(f"| {BLOCKS.get(b, b)} | {rows[b]} | {fmt(c['LUT'])} | {fmt(c['FF'])} | "
                   f"{fmt(c['BRAM36'])} | {fmt(c['DSP'])} |")
    out += ["", "The rest (MMCM, 4 x 2 OSERDESE2, OBUFDS, BUFG, I/O buffers, reset and LED logic) "
            "is the board wrapper `rtl/board/top_level.sv`.", "",
            "No timing numbers: Yosys maps to 7-series cells but does not place, route or "
            "time them, and no open-source flow gives timing sign-off for this part. "
            "The design has not been run on a real board."]
    print("\n".join(out))
    if "--check" in sys.argv:
        over = [k for k in CAPACITY if total[k] > CAPACITY[k]]
        if over:
            sys.exit(f"does not fit the XC7S50: {over}")


if __name__ == "__main__":
    main()
